In [2]:
#--Importing python libraries for data manipulation and analysis.
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
#--Importing table1 of sheet1 data from an excel file into a Pandas DataFrame(df_Table1).
df_Table1 = pd.read_excel("D:\\Divya\Python Classes\\Project\\Project_18.11.2024\\Campaign data.xlsx")

In [4]:
#--Fetching out data's in table1.
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [5]:
#--Importing table2 of sheet2 data from an excel file into a Pandas DataFrame(df_Table2).
df_Table2 = pd.read_excel("D:\\Divya\Python Classes\\Project\\Project_18.11.2024\\Campaign data.xlsx", sheet_name = "Table 2")

In [6]:
#--Fetching out data's in table2.
df_Table2

                 Campaign   Message type        Model
0       Sentra campaign 2  Future Market       Sentra
1       Sentra campaign 4  Future Market       Sentra
2       Sentra campaign 3  Future Market       Sentra
3       Sentra campaign 1  Future Market       Sentra
4       Altima campaign 1  Future Market       Altima
5       Altima campaign 5  Future Market       Altima
6       Altima campaign 4  Future Market       Altima
7       Altima campaign 6  Future Market       Altima
8        Kicks campaign 6  Future Market        Kicks
9        Kicks campaign 5  Future Market        Kicks
10       Rogue campaign 1  Future Market        Rogue
11       Rogue campaign 3  Future Market        Rogue
12       Rogue pre launch  Future Market        Rogue
13       Rogue campaign 5  Future Market        Rogue
14       Rogue campaign 4  Future Market        Rogue
15  Pathfinder campaign 3    Near Market   Pathfinder
16      Armada campaign 1    Near Market       Armada
17  Pathfinder campaign 8    Near Market   Pathfinder
18  Pathfinder campaign 5    Near Market   Pathfinder
19  Pathfinder campaign 6    Near Market   Pathfinder
20  Pathfinder campaign 7    Near Market   Pathfinder
21      Altima campaign 3  Future Market       Altima
22      Altima campaign 2  Future Market       Altima
23      Altima campaign 7    Near Market       Altima
24      Altima campaign 8    Near Market       Altima
25       Rogue campaign 2  Future Market        Rogue
26       Kicks campaign 3  Future Market        Kicks
27       Kicks campaign 4  Future Market        Kicks
28  Pathfinder campaign 2    Near Market   Pathfinder
29  Pathfinder campaign 1    Near Market   Pathfinder
30  Pathfinder campaign 4    Near Market   Pathfinder
31           shop at home  Future Market  Multi-Model
32       Kicks campaign 2    Near Market        Kicks
33       Kicks campaign 1    Near Market        Kicks
34      Armada campaign 2    Near Market       Armada
35      Armada campaign 4    Near Market       Armada
36      Armada campaign 3    Near Market       Armada
37     Sentra campaign 11    Near Market       Sentra
38     Sentra campaign 14    Near Market       Sentra
39     Sentra campaign 20    Near Market       Sentra
40     Sentra campaign 21    Near Market       Sentra
41      Sentra campaign 9    Near Market       Sentra
42      Sentra campaign 7    Near Market       Sentra
43      Sentra campaign 6    Near Market       Sentra
44     Sentra campaign 12    Near Market       Sentra
45     Sentra campaign 19    Near Market       Sentra
46     Sentra campaign 18    Near Market       Sentra
47     Sentra campaign 22    Near Market       Sentra
48     Sentra campaign 23    Near Market       Sentra
49     Sentra campaign 25    Near Market       Sentra
50      Sentra campaign 5    Near Market       Sentra
51     Sentra campaign 13    Near Market       Sentra
52     Sentra campaign 15    Near Market       Sentra
53      Sentra campaign 8    Near Market       Sentra
54     Sentra campaign 10    Near Market       Sentra
55     Sentra campaign 24    Near Market       Sentra
56     Sentra campaign 16    Near Market       Sentra
57     Sentra campaign 17    Near Market       Sentra

In [7]:
#--Checking for the number of rows and columns in table1. 
df_Table1.shape

(123699, 7)

In [8]:
#--Checking for the duplicates in table1.
df_Table1[df_Table1.duplicated()]

,Date,Data source,Campaign,Media Type,City,Metric,Value
80807,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80858,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80907,2021-03-29,Pinterest,shop at home,Display,Utica,Impressions,750.00
80908,2021-03-29,Pinterest,shop at home,Display,Utica,Media Cost,5.33
80909,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
...,...,...,...,...,...,...,...
122584,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Media Cost,0.00
122585,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Clicks,0.00
122586,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Impressions,2.00
122587,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Media Cost,0.00
122588,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Clicks,0.00

In [9]:
#--Removing the duplicate rows in table1.
df_Table1.drop_duplicates(inplace = True)

In [10]:
#--Checking for the number of rows and columns in table1 afetr removing the duplicates.
df_Table1.shape

(122629, 7)

In [11]:
#--Checking for the number of rows and columns in table2. 
df_Table2.shape

(58, 3)

In [12]:
#--Checking for the duplicates in table2.
df_Table2[df_Table2.duplicated()]

Empty DataFrame
Columns: [Campaign, Message type, Model]
Index: []

In [13]:
#--In table2 there is no duplicate data's, so dropping the duplicates step is not required here.

In [14]:
#--1.Find out the top 5 months in terms of impressions?

In [15]:
#--Step1.Converting the date format.
df_Table1['Date'] = pd.to_datetime(df_Table1['Date'])
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [16]:
#--Step2.Segregating day, month and year columns respectively.
df_Table1['Day'] = df_Table1['Date'].dt.day
df_Table1['month'] = df_Table1['Date'].dt.month
df_Table1['year'] = df_Table1['Date'].dt.year
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [17]:
#--Step3.Filtering 'Impressions' value from the 'Metric' column.
df1_Table1 = df_Table1[df_Table1['Metric'] == 'Impressions']
df1_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [18]:
#--Step4.Using groupby extracting data's of 'Impressions' value from the 'Metric' column for all the months and year.
df2_Table1 = (df1_Table1.groupby(['month','Metric','year'])['Value'].sum()).sort_values(ascending = False).reset_index()
df2_Table1

    month       Metric  year        Value
0       9  Impressions  2021  165961494.0
1      10  Impressions  2020  129386691.0
2       8  Impressions  2021  110579025.0
3       3  Impressions  2021  101719848.0
4       2  Impressions  2020   61351689.0
5       3  Impressions  2020   57768334.0
6      12  Impressions  2020   54048418.0
7       1  Impressions  2021   41756178.0
8       2  Impressions  2021   34320460.0
9       9  Impressions  2020   29477044.0
10     11  Impressions  2020   28514591.0
11      4  Impressions  2021   20774716.0
12      8  Impressions  2020    6720508.0
13      7  Impressions  2020    5341296.0
14      6  Impressions  2020     579534.0
15      5  Impressions  2021      17589.0
16      7  Impressions  2021      10358.0
17      4  Impressions  2020       9999.0
18      6  Impressions  2021       9154.0
19      5  Impressions  2020       8448.0
20      1  Impressions  2020         53.0
21     12  Impressions  2019         15.0

In [19]:
#--Step5.Extracting top 5 months in terms of'Impressions'.
df2_Table1.head(5)

   month       Metric  year        Value
0      9  Impressions  2021  165961494.0
1     10  Impressions  2020  129386691.0
2      8  Impressions  2021  110579025.0
3      3  Impressions  2021  101719848.0
4      2  Impressions  2020   61351689.0

In [20]:
#--2.Which model has maximum impressions?

In [21]:
#--Step1.Merging two tables using primary key.
dfmerge_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [22]:
#--Step2.Filtering 'Impressions' value from the 'Metric' column.
df3_Table1 = dfmerge_table[dfmerge_table['Metric'] == 'Impressions']
df3_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [64]:
#--Step3.Using groupby extracting data's of 'Impressions' value from the 'Metric' column for all the 'model'.
(df3_Table1.groupby(['Model','Metric'])['Value'].sum()).sort_values(ascending = False).reset_index()

         Model       Metric        Value
0   Pathfinder  Impressions  275832034.0
1       Armada  Impressions  175569709.0
2        Rogue  Impressions  132109157.0
3       Altima  Impressions   99823376.0
4        Kicks  Impressions   95929225.0
5       Sentra  Impressions   64176011.0
6  Multi-Model  Impressions    4915930.0

In [65]:
#--Step4.Extracting 'model' for maximum 'Impressions'.
(df3_Table1.groupby(['Model','Metric'])['Value'].sum()).sort_values(ascending = False).reset_index().head(1)

        Model       Metric        Value
0  Pathfinder  Impressions  275832034.0

In [66]:
#--3.Find out the top 3 campaigns in terms of impressions for every message type.

In [26]:
#--Step1.Merging two tables using primary key.
dfmerge1_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge1_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [27]:
#--Step2.Filtering 'Impressions' value from the 'Metric' column.
df4_Table1 = dfmerge1_table[dfmerge1_table['Metric'] == 'Impressions']
df4_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [28]:
#--Step3.Extracting 'Campaign' value counts in terms of 'Impressions' for every message type using groupby.
df5_Table1 = df4_Table1.groupby(['Message type','Metric','Campaign'])['Value'].sum().reset_index()
df5_Table1

     Message type       Metric               Campaign        Value
0   Future Market  Impressions      Altima campaign 1   35863660.0
1   Future Market  Impressions      Altima campaign 2    7200627.0
2   Future Market  Impressions      Altima campaign 3   45451489.0
3   Future Market  Impressions      Altima campaign 4     380995.0
4   Future Market  Impressions      Altima campaign 5    1176593.0
5   Future Market  Impressions      Altima campaign 6    1533773.0
6   Future Market  Impressions       Kicks campaign 3   27167086.0
7   Future Market  Impressions       Kicks campaign 4   33664998.0
8   Future Market  Impressions       Kicks campaign 5    1981485.0
9   Future Market  Impressions       Kicks campaign 6   32993380.0
10  Future Market  Impressions       Rogue campaign 1   18925107.0
11  Future Market  Impressions       Rogue campaign 2   25647766.0
12  Future Market  Impressions       Rogue campaign 3    4774134.0
13  Future Market  Impressions       Rogue campaign 4   32510217.0
14  Future Market  Impressions       Rogue campaign 5   33448074.0
15  Future Market  Impressions       Rogue pre launch   16803859.0
16  Future Market  Impressions      Sentra campaign 1    3119542.0
17  Future Market  Impressions      Sentra campaign 2     193569.0
18  Future Market  Impressions      Sentra campaign 3    5512548.0
19  Future Market  Impressions      Sentra campaign 4     196841.0
20  Future Market  Impressions           shop at home    4915930.0
21    Near Market  Impressions      Altima campaign 7    2043425.0
22    Near Market  Impressions      Altima campaign 8    6172814.0
23    Near Market  Impressions      Armada campaign 1    1799471.0
24    Near Market  Impressions      Armada campaign 2  118817195.0
25    Near Market  Impressions      Armada campaign 3   17482050.0
26    Near Market  Impressions      Armada campaign 4   37470993.0
27    Near Market  Impressions       Kicks campaign 1     120791.0
28    Near Market  Impressions       Kicks campaign 2       1485.0
29    Near Market  Impressions  Pathfinder campaign 1   48923126.0
30    Near Market  Impressions  Pathfinder campaign 2  115286607.0
31    Near Market  Impressions  Pathfinder campaign 3    3977697.0
32    Near Market  Impressions  Pathfinder campaign 4    5605811.0
33    Near Market  Impressions  Pathfinder campaign 5   17292561.0
34    Near Market  Impressions  Pathfinder campaign 6   51823574.0
35    Near Market  Impressions  Pathfinder campaign 7   16733721.0
36    Near Market  Impressions  Pathfinder campaign 8   16188937.0
37    Near Market  Impressions     Sentra campaign 10     859107.0
38    Near Market  Impressions     Sentra campaign 11    7803599.0
39    Near Market  Impressions     Sentra campaign 12    3102923.0
40    Near Market  Impressions     Sentra campaign 13     922310.0
41    Near Market  Impressions     Sentra campaign 14    7100167.0
42    Near Market  Impressions     Sentra campaign 15    2125984.0
43    Near Market  Impressions     Sentra campaign 16    1619686.0
44    Near Market  Impressions     Sentra campaign 17    1053431.0
45    Near Market  Impressions     Sentra campaign 18    2493519.0
46    Near Market  Impressions     Sentra campaign 19    2005235.0
47    Near Market  Impressions     Sentra campaign 20    3076545.0
48    Near Market  Impressions     Sentra campaign 21    3122121.0
49    Near Market  Impressions     Sentra campaign 22    2920814.0
50    Near Market  Impressions     Sentra campaign 23    1870596.0
51    Near Market  Impressions     Sentra campaign 24    1555632.0
52    Near Market  Impressions     Sentra campaign 25    1704259.0
53    Near Market  Impressions      Sentra campaign 5    1137379.0
54    Near Market  Impressions      Sentra campaign 6    2963379.0
55    Near Market  Impressions      Sentra campaign 7    3986238.0
56    Near Market  Impressions      Sentra campaign 8    1356458.0
57    Near Market  Impressions      Sentra campaign 9    2374129.0

In [29]:
#--Step4.Sorting out the 'Value' column.
df6_Table1 = df5_Table1.sort_values(by = 'Value', ascending = False)
df6_Table1

     Message type       Metric               Campaign        Value
24    Near Market  Impressions      Armada campaign 2  118817195.0
30    Near Market  Impressions  Pathfinder campaign 2  115286607.0
34    Near Market  Impressions  Pathfinder campaign 6   51823574.0
29    Near Market  Impressions  Pathfinder campaign 1   48923126.0
2   Future Market  Impressions      Altima campaign 3   45451489.0
26    Near Market  Impressions      Armada campaign 4   37470993.0
0   Future Market  Impressions      Altima campaign 1   35863660.0
7   Future Market  Impressions       Kicks campaign 4   33664998.0
14  Future Market  Impressions       Rogue campaign 5   33448074.0
9   Future Market  Impressions       Kicks campaign 6   32993380.0
13  Future Market  Impressions       Rogue campaign 4   32510217.0
6   Future Market  Impressions       Kicks campaign 3   27167086.0
11  Future Market  Impressions       Rogue campaign 2   25647766.0
10  Future Market  Impressions       Rogue campaign 1   18925107.0
25    Near Market  Impressions      Armada campaign 3   17482050.0
33    Near Market  Impressions  Pathfinder campaign 5   17292561.0
15  Future Market  Impressions       Rogue pre launch   16803859.0
35    Near Market  Impressions  Pathfinder campaign 7   16733721.0
36    Near Market  Impressions  Pathfinder campaign 8   16188937.0
38    Near Market  Impressions     Sentra campaign 11    7803599.0
1   Future Market  Impressions      Altima campaign 2    7200627.0
41    Near Market  Impressions     Sentra campaign 14    7100167.0
22    Near Market  Impressions      Altima campaign 8    6172814.0
32    Near Market  Impressions  Pathfinder campaign 4    5605811.0
18  Future Market  Impressions      Sentra campaign 3    5512548.0
20  Future Market  Impressions           shop at home    4915930.0
12  Future Market  Impressions       Rogue campaign 3    4774134.0
55    Near Market  Impressions      Sentra campaign 7    3986238.0
31    Near Market  Impressions  Pathfinder campaign 3    3977697.0
48    Near Market  Impressions     Sentra campaign 21    3122121.0
16  Future Market  Impressions      Sentra campaign 1    3119542.0
39    Near Market  Impressions     Sentra campaign 12    3102923.0
47    Near Market  Impressions     Sentra campaign 20    3076545.0
54    Near Market  Impressions      Sentra campaign 6    2963379.0
49    Near Market  Impressions     Sentra campaign 22    2920814.0
45    Near Market  Impressions     Sentra campaign 18    2493519.0
57    Near Market  Impressions      Sentra campaign 9    2374129.0
42    Near Market  Impressions     Sentra campaign 15    2125984.0
21    Near Market  Impressions      Altima campaign 7    2043425.0
46    Near Market  Impressions     Sentra campaign 19    2005235.0
8   Future Market  Impressions       Kicks campaign 5    1981485.0
50    Near Market  Impressions     Sentra campaign 23    1870596.0
23    Near Market  Impressions      Armada campaign 1    1799471.0
52    Near Market  Impressions     Sentra campaign 25    1704259.0
43    Near Market  Impressions     Sentra campaign 16    1619686.0
51    Near Market  Impressions     Sentra campaign 24    1555632.0
5   Future Market  Impressions      Altima campaign 6    1533773.0
56    Near Market  Impressions      Sentra campaign 8    1356458.0
4   Future Market  Impressions      Altima campaign 5    1176593.0
53    Near Market  Impressions      Sentra campaign 5    1137379.0
44    Near Market  Impressions     Sentra campaign 17    1053431.0
40    Near Market  Impressions     Sentra campaign 13     922310.0
37    Near Market  Impressions     Sentra campaign 10     859107.0
3   Future Market  Impressions      Altima campaign 4     380995.0
19  Future Market  Impressions      Sentra campaign 4     196841.0
17  Future Market  Impressions      Sentra campaign 2     193569.0
27    Near Market  Impressions       Kicks campaign 1     120791.0
28    Near Market  Impressions       Kicks campaign 2       1485.0

In [30]:
#--Step5.Extracting top 3 'Campaign' in terms of 'Impressions' for every message type.
df6_Table1.groupby(['Message type']).head(3).reset_index()

   index   Message type       Metric               Campaign        Value
0     24    Near Market  Impressions      Armada campaign 2  118817195.0
1     30    Near Market  Impressions  Pathfinder campaign 2  115286607.0
2     34    Near Market  Impressions  Pathfinder campaign 6   51823574.0
3      2  Future Market  Impressions      Altima campaign 3   45451489.0
4      0  Future Market  Impressions      Altima campaign 1   35863660.0
5      7  Future Market  Impressions       Kicks campaign 4   33664998.0

In [31]:
#--4.Does the campaign with maximum impressions also have maximum clicks?

In [32]:
#--Step1.Filtering 'Impressions' and 'Clicks' value from the 'Metric' column.
df6_Table1 = df_Table1[df_Table1['Metric'].isin(['Impressions', 'Clicks'])]
df6_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
5,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Clicks,0.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123692,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Clicks,102.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.0,30,9,2021

In [71]:
#--Step2.Using group by to extract the 'Campaign' with maximum 'Impressions' and 'Clicks'.
df7_Table1 = (df6_Table1.groupby(['Metric','Campaign'])['Value'].sum()).sort_values(ascending = False).reset_index()
df7_Table1

          Metric               Campaign        Value
0    Impressions      Armada campaign 2  118817195.0
1    Impressions  Pathfinder campaign 2  115286607.0
2    Impressions  Pathfinder campaign 6   51823574.0
3    Impressions  Pathfinder campaign 1   48923126.0
4    Impressions      Altima campaign 3   45451489.0
..           ...                    ...          ...
111       Clicks     Sentra campaign 13        498.0
112       Clicks     Sentra campaign 10        411.0
113       Clicks       Kicks campaign 1         25.0
114       Clicks       Kicks campaign 2          7.0
115       Clicks      Armada campaign 1          0.0

[116 rows x 3 columns]

In [77]:
#--Step3.Extracting 'Campaign' with maximum 'Impressions' and 'Campaign' with maximum 'Clicks'.
     #--No,campaign with maximum impressions also have maximum clicks.
df7_Table1.groupby(['Metric']).head(1).reset_index()

   index       Metric           Campaign        Value
0      0  Impressions  Armada campaign 2  118817195.0
1     54       Clicks  Armada campaign 2     241938.0

In [35]:
#--5.Find out the top 3 campaigns in terms of CPM (CPM stands for cost per mile which means cost per 1000 impressions. 
#--CPM = total media cost/total impressions * 1000)

In [36]:
#--Step1.Filtering 'Impressions' value from the 'Metric' column.
df8_Table1 = df_Table1[df_Table1['Metric'] == 'Impressions']
df8_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [37]:
#--Step2.Creating a new column as 'Total Impressions' in terms of 'Impressions' and 'Campaign'.
df9_Table1 = df8_Table1.groupby(['Campaign','Metric'])['Value'].sum().reset_index(name='Total Impressions')
df9_Table1

                 Campaign       Metric  Total Impressions
0       Altima campaign 1  Impressions         35863660.0
1       Altima campaign 2  Impressions          7200627.0
2       Altima campaign 3  Impressions         45451489.0
3       Altima campaign 4  Impressions           380995.0
4       Altima campaign 5  Impressions          1176593.0
5       Altima campaign 6  Impressions          1533773.0
6       Altima campaign 7  Impressions          2043425.0
7       Altima campaign 8  Impressions          6172814.0
8       Armada campaign 1  Impressions          1799471.0
9       Armada campaign 2  Impressions        118817195.0
10      Armada campaign 3  Impressions         17482050.0
11      Armada campaign 4  Impressions         37470993.0
12       Kicks campaign 1  Impressions           120791.0
13       Kicks campaign 2  Impressions             1485.0
14       Kicks campaign 3  Impressions         27167086.0
15       Kicks campaign 4  Impressions         33664998.0
16       Kicks campaign 5  Impressions          1981485.0
17       Kicks campaign 6  Impressions         32993380.0
18  Pathfinder campaign 1  Impressions         48923126.0
19  Pathfinder campaign 2  Impressions        115286607.0
20  Pathfinder campaign 3  Impressions          3977697.0
21  Pathfinder campaign 4  Impressions          5605811.0
22  Pathfinder campaign 5  Impressions         17292561.0
23  Pathfinder campaign 6  Impressions         51823574.0
24  Pathfinder campaign 7  Impressions         16733721.0
25  Pathfinder campaign 8  Impressions         16188937.0
26       Rogue campaign 1  Impressions         18925107.0
27       Rogue campaign 2  Impressions         25647766.0
28       Rogue campaign 3  Impressions          4774134.0
29       Rogue campaign 4  Impressions         32510217.0
30       Rogue campaign 5  Impressions         33448074.0
31       Rogue pre launch  Impressions         16803859.0
32      Sentra campaign 1  Impressions          3119542.0
33     Sentra campaign 10  Impressions           859107.0
34     Sentra campaign 11  Impressions          7803599.0
35     Sentra campaign 12  Impressions          3102923.0
36     Sentra campaign 13  Impressions           922310.0
37     Sentra campaign 14  Impressions          7100167.0
38     Sentra campaign 15  Impressions          2125984.0
39     Sentra campaign 16  Impressions          1619686.0
40     Sentra campaign 17  Impressions          1053431.0
41     Sentra campaign 18  Impressions          2493519.0
42     Sentra campaign 19  Impressions          2005235.0
43      Sentra campaign 2  Impressions           193569.0
44     Sentra campaign 20  Impressions          3076545.0
45     Sentra campaign 21  Impressions          3122121.0
46     Sentra campaign 22  Impressions          2920814.0
47     Sentra campaign 23  Impressions          1870596.0
48     Sentra campaign 24  Impressions          1555632.0
49     Sentra campaign 25  Impressions          1704259.0
50      Sentra campaign 3  Impressions          5512548.0
51      Sentra campaign 4  Impressions           196841.0
52      Sentra campaign 5  Impressions          1137379.0
53      Sentra campaign 6  Impressions          2963379.0
54      Sentra campaign 7  Impressions          3986238.0
55      Sentra campaign 8  Impressions          1356458.0
56      Sentra campaign 9  Impressions          2374129.0
57           shop at home  Impressions          4915930.0

In [38]:
#--Step3.Sorting the 'Total Impressions' values.
df10_Table1 = df9_Table1.sort_values(by='Total Impressions', ascending=False)
df10_Table1

                 Campaign       Metric  Total Impressions
9       Armada campaign 2  Impressions        118817195.0
19  Pathfinder campaign 2  Impressions        115286607.0
23  Pathfinder campaign 6  Impressions         51823574.0
18  Pathfinder campaign 1  Impressions         48923126.0
2       Altima campaign 3  Impressions         45451489.0
11      Armada campaign 4  Impressions         37470993.0
0       Altima campaign 1  Impressions         35863660.0
15       Kicks campaign 4  Impressions         33664998.0
30       Rogue campaign 5  Impressions         33448074.0
17       Kicks campaign 6  Impressions         32993380.0
29       Rogue campaign 4  Impressions         32510217.0
14       Kicks campaign 3  Impressions         27167086.0
27       Rogue campaign 2  Impressions         25647766.0
26       Rogue campaign 1  Impressions         18925107.0
10      Armada campaign 3  Impressions         17482050.0
22  Pathfinder campaign 5  Impressions         17292561.0
31       Rogue pre launch  Impressions         16803859.0
24  Pathfinder campaign 7  Impressions         16733721.0
25  Pathfinder campaign 8  Impressions         16188937.0
34     Sentra campaign 11  Impressions          7803599.0
1       Altima campaign 2  Impressions          7200627.0
37     Sentra campaign 14  Impressions          7100167.0
7       Altima campaign 8  Impressions          6172814.0
21  Pathfinder campaign 4  Impressions          5605811.0
50      Sentra campaign 3  Impressions          5512548.0
57           shop at home  Impressions          4915930.0
28       Rogue campaign 3  Impressions          4774134.0
54      Sentra campaign 7  Impressions          3986238.0
20  Pathfinder campaign 3  Impressions          3977697.0
45     Sentra campaign 21  Impressions          3122121.0
32      Sentra campaign 1  Impressions          3119542.0
35     Sentra campaign 12  Impressions          3102923.0
44     Sentra campaign 20  Impressions          3076545.0
53      Sentra campaign 6  Impressions          2963379.0
46     Sentra campaign 22  Impressions          2920814.0
41     Sentra campaign 18  Impressions          2493519.0
56      Sentra campaign 9  Impressions          2374129.0
38     Sentra campaign 15  Impressions          2125984.0
6       Altima campaign 7  Impressions          2043425.0
42     Sentra campaign 19  Impressions          2005235.0
16       Kicks campaign 5  Impressions          1981485.0
47     Sentra campaign 23  Impressions          1870596.0
8       Armada campaign 1  Impressions          1799471.0
49     Sentra campaign 25  Impressions          1704259.0
39     Sentra campaign 16  Impressions          1619686.0
48     Sentra campaign 24  Impressions          1555632.0
5       Altima campaign 6  Impressions          1533773.0
55      Sentra campaign 8  Impressions          1356458.0
4       Altima campaign 5  Impressions          1176593.0
52      Sentra campaign 5  Impressions          1137379.0
40     Sentra campaign 17  Impressions          1053431.0
36     Sentra campaign 13  Impressions           922310.0
33     Sentra campaign 10  Impressions           859107.0
3       Altima campaign 4  Impressions           380995.0
51      Sentra campaign 4  Impressions           196841.0
43      Sentra campaign 2  Impressions           193569.0
12       Kicks campaign 1  Impressions           120791.0
13       Kicks campaign 2  Impressions             1485.0

In [39]:
#--Step4.Filtering 'Media Cost' value from the 'Metric' column.
df11_Table1 = df_Table1[df_Table1['Metric'] == 'Media Cost']
df11_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123685,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021
123688,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021
123691,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021

In [40]:
#--Step5.Creating a new column as 'Total Media Cost' in terms of 'Media Cost' and 'Campaign'.
df12_Table1 = df11_Table1.groupby(['Campaign','Metric'])['Value'].sum().reset_index(name='Total Media Cost')
df12_Table1

                 Campaign      Metric  Total Media Cost
0       Altima campaign 1  Media Cost         489477.29
1       Altima campaign 2  Media Cost          74693.85
2       Altima campaign 3  Media Cost         376369.35
3       Altima campaign 4  Media Cost           6000.05
4       Altima campaign 5  Media Cost          18391.45
5       Altima campaign 6  Media Cost          13033.96
6       Altima campaign 7  Media Cost          19614.55
7       Altima campaign 8  Media Cost          47398.70
8       Armada campaign 1  Media Cost           8210.77
9       Armada campaign 2  Media Cost         698093.58
10      Armada campaign 3  Media Cost         145040.71
11      Armada campaign 4  Media Cost         298919.40
12       Kicks campaign 1  Media Cost              0.00
13       Kicks campaign 2  Media Cost              0.00
14       Kicks campaign 3  Media Cost         181003.85
15       Kicks campaign 4  Media Cost         181523.37
16       Kicks campaign 5  Media Cost          28367.02
17       Kicks campaign 6  Media Cost         370962.96
18  Pathfinder campaign 1  Media Cost         261944.37
19  Pathfinder campaign 2  Media Cost         689604.29
20  Pathfinder campaign 3  Media Cost          73584.37
21  Pathfinder campaign 4  Media Cost          48319.02
22  Pathfinder campaign 5  Media Cost         316442.90
23  Pathfinder campaign 6  Media Cost         797639.63
24  Pathfinder campaign 7  Media Cost         304427.70
25  Pathfinder campaign 8  Media Cost         292833.90
26       Rogue campaign 1  Media Cost         218075.42
27       Rogue campaign 2  Media Cost         244984.76
28       Rogue campaign 3  Media Cost          26924.74
29       Rogue campaign 4  Media Cost         484928.76
30       Rogue campaign 5  Media Cost         224408.94
31       Rogue pre launch  Media Cost         150000.03
32      Sentra campaign 1  Media Cost          13630.70
33     Sentra campaign 10  Media Cost          10411.61
34     Sentra campaign 11  Media Cost          91388.52
35     Sentra campaign 12  Media Cost          36425.55
36     Sentra campaign 13  Media Cost          10389.33
37     Sentra campaign 14  Media Cost          82237.26
38     Sentra campaign 15  Media Cost          24804.88
39     Sentra campaign 16  Media Cost          18825.91
40     Sentra campaign 17  Media Cost          12684.74
41     Sentra campaign 18  Media Cost          30050.35
42     Sentra campaign 19  Media Cost          23108.76
43      Sentra campaign 2  Media Cost            719.29
44     Sentra campaign 20  Media Cost          33861.55
45     Sentra campaign 21  Media Cost          35633.19
46     Sentra campaign 22  Media Cost          32146.12
47     Sentra campaign 23  Media Cost          22497.44
48     Sentra campaign 24  Media Cost          18335.60
49     Sentra campaign 25  Media Cost          20103.59
50      Sentra campaign 3  Media Cost          54522.30
51      Sentra campaign 4  Media Cost           1889.31
52      Sentra campaign 5  Media Cost          13532.28
53      Sentra campaign 6  Media Cost          34295.78
54      Sentra campaign 7  Media Cost          46075.07
55      Sentra campaign 8  Media Cost          15547.71
56      Sentra campaign 9  Media Cost          28385.29
57           shop at home  Media Cost          51877.36

In [41]:
#--Step6.Sorting the 'Total Media Cost' values.
df13_Table1 = df12_Table1.sort_values(by='Total Media Cost', ascending=False)
df13_Table1

                 Campaign      Metric  Total Media Cost
23  Pathfinder campaign 6  Media Cost         797639.63
9       Armada campaign 2  Media Cost         698093.58
19  Pathfinder campaign 2  Media Cost         689604.29
0       Altima campaign 1  Media Cost         489477.29
29       Rogue campaign 4  Media Cost         484928.76
2       Altima campaign 3  Media Cost         376369.35
17       Kicks campaign 6  Media Cost         370962.96
22  Pathfinder campaign 5  Media Cost         316442.90
24  Pathfinder campaign 7  Media Cost         304427.70
11      Armada campaign 4  Media Cost         298919.40
25  Pathfinder campaign 8  Media Cost         292833.90
18  Pathfinder campaign 1  Media Cost         261944.37
27       Rogue campaign 2  Media Cost         244984.76
30       Rogue campaign 5  Media Cost         224408.94
26       Rogue campaign 1  Media Cost         218075.42
15       Kicks campaign 4  Media Cost         181523.37
14       Kicks campaign 3  Media Cost         181003.85
31       Rogue pre launch  Media Cost         150000.03
10      Armada campaign 3  Media Cost         145040.71
34     Sentra campaign 11  Media Cost          91388.52
37     Sentra campaign 14  Media Cost          82237.26
1       Altima campaign 2  Media Cost          74693.85
20  Pathfinder campaign 3  Media Cost          73584.37
50      Sentra campaign 3  Media Cost          54522.30
57           shop at home  Media Cost          51877.36
21  Pathfinder campaign 4  Media Cost          48319.02
7       Altima campaign 8  Media Cost          47398.70
54      Sentra campaign 7  Media Cost          46075.07
35     Sentra campaign 12  Media Cost          36425.55
45     Sentra campaign 21  Media Cost          35633.19
53      Sentra campaign 6  Media Cost          34295.78
44     Sentra campaign 20  Media Cost          33861.55
46     Sentra campaign 22  Media Cost          32146.12
41     Sentra campaign 18  Media Cost          30050.35
56      Sentra campaign 9  Media Cost          28385.29
16       Kicks campaign 5  Media Cost          28367.02
28       Rogue campaign 3  Media Cost          26924.74
38     Sentra campaign 15  Media Cost          24804.88
42     Sentra campaign 19  Media Cost          23108.76
47     Sentra campaign 23  Media Cost          22497.44
49     Sentra campaign 25  Media Cost          20103.59
6       Altima campaign 7  Media Cost          19614.55
39     Sentra campaign 16  Media Cost          18825.91
4       Altima campaign 5  Media Cost          18391.45
48     Sentra campaign 24  Media Cost          18335.60
55      Sentra campaign 8  Media Cost          15547.71
32      Sentra campaign 1  Media Cost          13630.70
52      Sentra campaign 5  Media Cost          13532.28
5       Altima campaign 6  Media Cost          13033.96
40     Sentra campaign 17  Media Cost          12684.74
33     Sentra campaign 10  Media Cost          10411.61
36     Sentra campaign 13  Media Cost          10389.33
8       Armada campaign 1  Media Cost           8210.77
3       Altima campaign 4  Media Cost           6000.05
51      Sentra campaign 4  Media Cost           1889.31
43      Sentra campaign 2  Media Cost            719.29
13       Kicks campaign 2  Media Cost              0.00
12       Kicks campaign 1  Media Cost              0.00

In [42]:
#--Step7.Merging 'Total Impressions' and 'Total Media Cost' in terms of 'Campaign'.
dfmerge2_table = pd.merge(df10_Table1 , df13_Table1 , on = 'Campaign')
dfmerge2_table

,Campaign,Metric_x,Total Impressions,Metric_y,Total Media Cost
0,Armada campaign 2,Impressions,118817195.0,Media Cost,698093.58
1,Pathfinder campaign 2,Impressions,115286607.0,Media Cost,689604.29
2,Pathfinder campaign 6,Impressions,51823574.0,Media Cost,797639.63
3,Pathfinder campaign 1,Impressions,48923126.0,Media Cost,261944.37
4,Altima campaign 3,Impressions,45451489.0,Media Cost,376369.35
5,Armada campaign 4,Impressions,37470993.0,Media Cost,298919.40
6,Altima campaign 1,Impressions,35863660.0,Media Cost,489477.29
7,Kicks campaign 4,Impressions,33664998.0,Media Cost,181523.37
8,Rogue campaign 5,Impressions,33448074.0,Media Cost,224408.94
9,Kicks campaign 6,Impressions,32993380.0,Media Cost,370962.96
10,Rogue campaign 4,Impressions,32510217.0,Media Cost,484928.76
11,Kicks campaign 3,Impressions,27167086.0,Media Cost,181003.85
12,Rogue campaign 2,Impressions,25647766.0,Media Cost,244984.76
13,Rogue campaign 1,Impressions,18925107.0,Media Cost,218075.42
14,Armada campaign 3,Impressions,17482050.0,Media Cost,145040.71
15,Pathfinder campaign 5,Impressions,17292561.0,Media Cost,316442.90
16,Rogue pre launch,Impressions,16803859.0,Media Cost,150000.03
17,Pathfinder campaign 7,Impressions,16733721.0,Media Cost,304427.70
18,Pathfinder campaign 8,Impressions,16188937.0,Media Cost,292833.90
19,Sentra campaign 11,Impressions,7803599.0,Media Cost,91388.52
20,Altima campaign 2,Impressions,7200627.0,Media Cost,74693.85
21,Sentra campaign 14,Impressions,7100167.0,Media Cost,82237.26
22,Altima campaign 8,Impressions,6172814.0,Media Cost,47398.70
23,Pathfinder campaign 4,Impressions,5605811.0,Media Cost,48319.02
24,Sentra campaign 3,Impressions,5512548.0,Media Cost,54522.30
25,shop at home,Impressions,4915930.0,Media Cost,51877.36
26,Rogue campaign 3,Impressions,4774134.0,Media Cost,26924.74
27,Sentra campaign 7,Impressions,3986238.0,Media Cost,46075.07
28,Pathfinder campaign 3,Impressions,3977697.0,Media Cost,73584.37
29,Sentra campaign 21,Impressions,3122121.0,Media Cost,35633.19
30,Sentra campaign 1,Impressions,3119542.0,Media Cost,13630.70
31,Sentra campaign 12,Impressions,3102923.0,Media Cost,36425.55
32,Sentra campaign 20,Impressions,3076545.0,Media Cost,33861.55
33,Sentra campaign 6,Impressions,2963379.0,Media Cost,34295.78
34,Sentra campaign 22,Impressions,2920814.0,Media Cost,32146.12
35,Sentra campaign 18,Impressions,2493519.0,Media Cost,30050.35
36,Sentra campaign 9,Impressions,2374129.0,Media Cost,28385.29
37,Sentra campaign 15,Impressions,2125984.0,Media Cost,24804.88
38,Altima campaign 7,Impressions,2043425.0,Media Cost,19614.55
39,Sentra campaign 19,Impressions,2005235.0,Media Cost,23108.76
40,Kicks campaign 5,Impressions,1981485.0,Media Cost,28367.02
41,Sentra campaign 23,Impressions,1870596.0,Media Cost,22497.44
42,Armada campaign 1,Impressions,1799471.0,Media Cost,8210.77
43,Sentra campaign 25,Impressions,1704259.0,Media Cost,20103.59
44,Sentra campaign 16,Impressions,1619686.0,Media Cost,18825.91
45,Sentra campaign 24,Impressions,1555632.0,Media Cost,18335.60
46,Altima campaign 6,Impressions,1533773.0,Media Cost,13033.96
47,Sentra campaign 8,Impressions,1356458.0,Media Cost,15547.71
48,Altima campaign 5,Impressions,1176593.0,Media Cost,18391.45
49,Sentra campaign 5,Impressions,1137379.0,Media Cost,13532.28
50,Sentra campaign 17,Impressions,1053431.0,Media Cost,12684.74
51,Sentra campaign 13,Impressions,922310.0,Media Cost,10389.33
52,Sentra campaign 10,Impressions,859107.0,Media Cost,10411.61
53,Altima campaign 4,Impressions,380995.0,Media Cost,6000.05
54,Sentra campaign 4,Impressions,196841.0,Media Cost,1889.31
55,Sentra campaign 2,Impressions,193569.0,Media Cost,719.29
56,Kicks campaign 1,Impressions,120791.0,Media Cost,0.00
57,Kicks campaign 2,Impressions,1485.0,Media Cost,0.00

In [43]:
#--Step8.Creating a new column as 'CPM' in terms 'Campaign'.
dfmerge2_table['CPM'] = (dfmerge2_table['Total Media Cost'] / dfmerge2_table['Total Impressions']) * 1000

In [44]:
#--Step9.Filtering top 3 'Campaign' in terms of 'CPM'. 
dfmerge2_table.sort_values(by = 'CPM', ascending = False).head(3)

,Campaign,Metric_x,Total Impressions,Metric_y,Total Media Cost,CPM
28,Pathfinder campaign 3,Impressions,3977697.0,Media Cost,73584.37,18.499240
15,Pathfinder campaign 5,Impressions,17292561.0,Media Cost,316442.90,18.299366
17,Pathfinder campaign 7,Impressions,16733721.0,Media Cost,304427.70,18.192469

In [45]:
#--6.What is the monthly average media cost for different media types?

In [46]:
#--Step1.Filtering 'Media Cost' value from the 'Metric' column.
df14_Table1 = df_Table1[df_Table1['Metric'] == 'Media Cost']
df14_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123685,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021
123688,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021
123691,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021

In [47]:
#--Step2.Extracting monthly average 'Media Cost' for different 'Media Type'.
df14_Table1.groupby(['month','year','Metric','Media Type'])['Value'].mean().reset_index()

    month  year      Metric    Media Type       Value
0       1  2020  Media Cost       Display    0.000000
1       1  2020  Media Cost  Online Video    0.000000
2       1  2021  Media Cost       Display    0.000000
3       1  2021  Media Cost  Online Video  129.927345
4       2  2020  Media Cost       Display  424.566390
5       2  2020  Media Cost  Online Video    0.000000
6       2  2021  Media Cost       Display    0.000000
7       2  2021  Media Cost  Online Video  180.083354
8       3  2020  Media Cost       Display  411.136057
9       3  2020  Media Cost  Online Video    8.695333
10      3  2021  Media Cost       Display    3.893718
11      3  2021  Media Cost  Online Video  186.902184
12      4  2020  Media Cost       Display    0.000000
13      4  2020  Media Cost  Online Video    0.000000
14      4  2021  Media Cost       Display   75.663433
15      4  2021  Media Cost  Online Video  172.286245
16      5  2020  Media Cost       Display    0.000000
17      5  2021  Media Cost       Display    0.000000
18      5  2021  Media Cost  Online Video    0.000000
19      6  2020  Media Cost       Display    0.000000
20      6  2020  Media Cost  Online Video    9.997719
21      6  2021  Media Cost       Display    0.000000
22      6  2021  Media Cost  Online Video    0.000000
23      7  2020  Media Cost       Display    0.000000
24      7  2020  Media Cost  Online Video   26.610211
25      7  2021  Media Cost       Display    0.000000
26      7  2021  Media Cost  Online Video    0.000000
27      8  2020  Media Cost       Display    0.000000
28      8  2020  Media Cost  Online Video   80.534931
29      8  2021  Media Cost       Display    0.000000
30      8  2021  Media Cost  Online Video  259.055211
31      9  2020  Media Cost       Display    0.000000
32      9  2020  Media Cost  Online Video  644.141190
33      9  2021  Media Cost       Display  211.265498
34      9  2021  Media Cost  Online Video  281.996328
35     10  2020  Media Cost       Display    0.000925
36     10  2020  Media Cost  Online Video  250.820020
37     11  2020  Media Cost       Display    0.000000
38     11  2020  Media Cost  Online Video  148.412704
39     12  2019  Media Cost       Display    0.000000
40     12  2019  Media Cost  Online Video    0.000000
41     12  2020  Media Cost       Display    0.000000
42     12  2020  Media Cost  Online Video  238.508465

In [81]:
#--Step2.Extracting 'Media Cost' in terms of 'Media Type'.
df14_Taable1 = (df14_Table1.groupby(['month','year','Metric','Media Type'])['Value'].mean()).sort_values(ascending = False).reset_index()
df14_Taable1

    month  year      Metric    Media Type       Value
0       9  2020  Media Cost  Online Video  644.141190
1       2  2020  Media Cost       Display  424.566390
2       3  2020  Media Cost       Display  411.136057
3       9  2021  Media Cost  Online Video  281.996328
4       8  2021  Media Cost  Online Video  259.055211
5      10  2020  Media Cost  Online Video  250.820020
6      12  2020  Media Cost  Online Video  238.508465
7       9  2021  Media Cost       Display  211.265498
8       3  2021  Media Cost  Online Video  186.902184
9       2  2021  Media Cost  Online Video  180.083354
10      4  2021  Media Cost  Online Video  172.286245
11     11  2020  Media Cost  Online Video  148.412704
12      1  2021  Media Cost  Online Video  129.927345
13      8  2020  Media Cost  Online Video   80.534931
14      4  2021  Media Cost       Display   75.663433
15      7  2020  Media Cost  Online Video   26.610211
16      6  2020  Media Cost  Online Video    9.997719
17      3  2020  Media Cost  Online Video    8.695333
18      3  2021  Media Cost       Display    3.893718
19     10  2020  Media Cost       Display    0.000925
20      8  2020  Media Cost       Display    0.000000
21     12  2019  Media Cost       Display    0.000000
22     12  2019  Media Cost  Online Video    0.000000
23      9  2020  Media Cost       Display    0.000000
24     12  2020  Media Cost       Display    0.000000
25      8  2021  Media Cost       Display    0.000000
26     11  2020  Media Cost       Display    0.000000
27      1  2020  Media Cost       Display    0.000000
28      7  2021  Media Cost  Online Video    0.000000
29      7  2021  Media Cost       Display    0.000000
30      7  2020  Media Cost       Display    0.000000
31      6  2021  Media Cost  Online Video    0.000000
32      1  2020  Media Cost  Online Video    0.000000
33      6  2020  Media Cost       Display    0.000000
34      5  2021  Media Cost  Online Video    0.000000
35      5  2021  Media Cost       Display    0.000000
36      5  2020  Media Cost       Display    0.000000
37      4  2020  Media Cost  Online Video    0.000000
38      4  2020  Media Cost       Display    0.000000
39      2  2021  Media Cost       Display    0.000000
40      2  2020  Media Cost  Online Video    0.000000
41      1  2021  Media Cost       Display    0.000000
42      6  2021  Media Cost       Display    0.000000

In [87]:
#--Step3.Extracting monthly average 'Media Cost' for different 'Media Type'.
df14_Taable1.groupby(['Media Type']).head(1).reset_index()

   index  month  year      Metric    Media Type      Value
0      0      9  2020  Media Cost  Online Video  644.14119
1      1      2  2020  Media Cost       Display  424.56639

In [50]:
#--7.Which media type is more expensive in terms of CPM?

In [51]:
#--Step1.Merging two tables using primary key.
dfmerge3_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge3_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [52]:
#--Step2.Checking for the unique values in 'Media Type'.
dfmerge3_table['Media Type'].unique()

array(['Display', 'Online Video'], dtype=object)

In [53]:
#--Step3.Filtering 'Media Cost' value from the 'Metric' column.
df15_Table1 = dfmerge3_table[dfmerge3_table['Metric'] == 'Media Cost']
df15_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019,Near Market,Kicks
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019,Near Market,Kicks
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122615,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021,Near Market,Pathfinder
122618,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021,Near Market,Pathfinder
122621,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021,Near Market,Pathfinder
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder

In [54]:
#--Step4.Creating a new column as 'Total Media Cost' in terms of 'Media Type'.
df16_Table1 = df15_Table1.groupby(['Media Type','Metric'])['Value'].sum().reset_index(name='Total Media Cost')
df16_Table1

     Media Type      Metric  Total Media Cost
0       Display  Media Cost        1017789.55
1  Online Video  Media Cost        6836809.63

In [55]:
#--Step5.Filtering 'Impressions' value from the 'Metric' column.
df17_Table1 = dfmerge3_table[dfmerge3_table['Metric'] == 'Impressions']
df17_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [56]:
#--Step6.Creating a new column as 'Total Impressions' in terms of 'Media Type'.
df18_Table1 = df17_Table1.groupby(['Media Type','Metric'])['Value'].sum().reset_index(name='Total Impressions')
df18_Table1

     Media Type       Metric  Total Impressions
0       Display  Impressions        174091539.0
1  Online Video  Impressions        674263903.0

In [57]:
#--Step7.Merging 'Total Impressions' and 'Total Media Cost' in terms of 'Media Type'.
dfmerge4_table = pd.merge(df16_Table1 , df18_Table1 , on = 'Media Type')
dfmerge4_table

     Media Type    Metric_x  Total Media Cost     Metric_y  Total Impressions
0       Display  Media Cost        1017789.55  Impressions        174091539.0
1  Online Video  Media Cost        6836809.63  Impressions        674263903.0

In [58]:
#--Step8.Creating a new column as 'CPM' in terms 'Media Type'.
dfmerge4_table['CPM'] = (dfmerge4_table['Total Media Cost'] / dfmerge4_table['Total Impressions']) * 1000
dfmerge4_table

,Media Type,Metric_x,Total Media Cost,Metric_y,Total Impressions,CPM
0,Display,Media Cost,1017789.55,Impressions,174091539.0,5.846290
1,Online Video,Media Cost,6836809.63,Impressions,674263903.0,10.139664

In [59]:
#--Step9.Sorting the 'CPM' values to find out the expensive 'Media Type'.
dfmerge4_table.sort_values(by='CPM', ascending=False)[:1]

,Media Type,Metric_x,Total Media Cost,Metric_y,Total Impressions,CPM
1,Online Video,Media Cost,6836809.63,Impressions,674263903.0,10.139664