In [1]:
#--Importing python libraries for data manipulation and analysis.
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
#--Importing table1 of sheet1 data from an excel file into a Pandas DataFrame(df_Table1).
df_Table1 = pd.read_excel("D:\\Divya\\Python Classes\\Project\\Campaign data.xlsx")

In [3]:
#--Fetching out data's in table1.
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [4]:
#--Importing table2 of sheet2 data from an excel file into a Pandas DataFrame(df_Table2).
df_Table2 = pd.read_excel("D:\\Divya\\Python Classes\\Project\\Campaign data.xlsx", sheet_name = "Table 2")

In [5]:
#--Fetching out data's in table2.
df_Table2

                 Campaign   Message type        Model
0       Sentra campaign 2  Future Market       Sentra
1       Sentra campaign 4  Future Market       Sentra
2       Sentra campaign 3  Future Market       Sentra
3       Sentra campaign 1  Future Market       Sentra
4       Altima campaign 1  Future Market       Altima
5       Altima campaign 5  Future Market       Altima
6       Altima campaign 4  Future Market       Altima
7       Altima campaign 6  Future Market       Altima
8        Kicks campaign 6  Future Market        Kicks
9        Kicks campaign 5  Future Market        Kicks
10       Rogue campaign 1  Future Market        Rogue
11       Rogue campaign 3  Future Market        Rogue
12       Rogue pre launch  Future Market        Rogue
13       Rogue campaign 5  Future Market        Rogue
14       Rogue campaign 4  Future Market        Rogue
15  Pathfinder campaign 3    Near Market   Pathfinder
16      Armada campaign 1    Near Market       Armada
17  Pathfinder campaign 8    Near Market   Pathfinder
18  Pathfinder campaign 5    Near Market   Pathfinder
19  Pathfinder campaign 6    Near Market   Pathfinder
20  Pathfinder campaign 7    Near Market   Pathfinder
21      Altima campaign 3  Future Market       Altima
22      Altima campaign 2  Future Market       Altima
23      Altima campaign 7    Near Market       Altima
24      Altima campaign 8    Near Market       Altima
25       Rogue campaign 2  Future Market        Rogue
26       Kicks campaign 3  Future Market        Kicks
27       Kicks campaign 4  Future Market        Kicks
28  Pathfinder campaign 2    Near Market   Pathfinder
29  Pathfinder campaign 1    Near Market   Pathfinder
30  Pathfinder campaign 4    Near Market   Pathfinder
31           shop at home  Future Market  Multi-Model
32       Kicks campaign 2    Near Market        Kicks
33       Kicks campaign 1    Near Market        Kicks
34      Armada campaign 2    Near Market       Armada
35      Armada campaign 4    Near Market       Armada
36      Armada campaign 3    Near Market       Armada
37     Sentra campaign 11    Near Market       Sentra
38     Sentra campaign 14    Near Market       Sentra
39     Sentra campaign 20    Near Market       Sentra
40     Sentra campaign 21    Near Market       Sentra
41      Sentra campaign 9    Near Market       Sentra
42      Sentra campaign 7    Near Market       Sentra
43      Sentra campaign 6    Near Market       Sentra
44     Sentra campaign 12    Near Market       Sentra
45     Sentra campaign 19    Near Market       Sentra
46     Sentra campaign 18    Near Market       Sentra
47     Sentra campaign 22    Near Market       Sentra
48     Sentra campaign 23    Near Market       Sentra
49     Sentra campaign 25    Near Market       Sentra
50      Sentra campaign 5    Near Market       Sentra
51     Sentra campaign 13    Near Market       Sentra
52     Sentra campaign 15    Near Market       Sentra
53      Sentra campaign 8    Near Market       Sentra
54     Sentra campaign 10    Near Market       Sentra
55     Sentra campaign 24    Near Market       Sentra
56     Sentra campaign 16    Near Market       Sentra
57     Sentra campaign 17    Near Market       Sentra

In [6]:
#--Checking for the number of rows and columns in table1. 
df_Table1.shape

(123699, 7)

In [7]:
#--Checking for the duplicates in table1.
df_Table1[df_Table1.duplicated()]

,Date,Data source,Campaign,Media Type,City,Metric,Value
80807,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80858,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80907,2021-03-29,Pinterest,shop at home,Display,Utica,Impressions,750.00
80908,2021-03-29,Pinterest,shop at home,Display,Utica,Media Cost,5.33
80909,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
...,...,...,...,...,...,...,...
122584,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Media Cost,0.00
122585,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Clicks,0.00
122586,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Impressions,2.00
122587,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Media Cost,0.00
122588,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Clicks,0.00

In [8]:
#--Removing the duplicate rows in table1.
df_Table1.drop_duplicates(inplace = True)

In [9]:
#--Checking for the number of rows and columns in table1 afetr removing the duplicates.
df_Table1.shape

(122629, 7)

In [10]:
#--Checking for the number of rows and columns in table2. 
df_Table2.shape

(58, 3)

In [11]:
#--Checking for the duplicates in table2.
df_Table2[df_Table2.duplicated()]

Empty DataFrame
Columns: [Campaign, Message type, Model]
Index: []

In [12]:
#--In table2 there is no duplicate data's, so dropping the duplicates step is not required here.

In [13]:
#--1.Find out the top 5 months in terms of impressions?

In [14]:
#--Step1.Converting the date format.
df_Table1['Date'] = pd.to_datetime(df_Table1['Date'])
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [15]:
#--Step2.Segregating day, month and year columns respectively.
df_Table1['Day'] = df_Table1['Date'].dt.day
df_Table1['month'] = df_Table1['Date'].dt.month
df_Table1['year'] = df_Table1['Date'].dt.year
df_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [16]:
#--Step3.Filtering 'Impressions' value from the 'Metric' column.
df1_Table1 = df_Table1[df_Table1['Metric'] == 'Impressions']
df1_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [17]:
#--Step4.Using groupby extracting data's of 'Impressions' value from the 'Metric' column for all the months.
df2_Table1 = df1_Table1.groupby('Metric')['month'].value_counts()
df2_Table1

Metric       month
Impressions  9        6929
             3        5784
             10       5719
             8        5651
             1        3119
             12       2877
             2        2631
             11       2330
             7        2134
             4        1706
             6        1168
             5         851
Name: count, dtype: int64

In [18]:
#--Step5.Extracting top 5 months in terms of'Impressions'.
df2_Table1.head(5)

Metric       month
Impressions  9        6929
             3        5784
             10       5719
             8        5651
             1        3119
Name: count, dtype: int64

In [19]:
#--2.Which model has maximum impressions?

In [20]:
#--Step1.Merging two tables using primary key.
dfmerge_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [21]:
#--Step2.Filtering 'Impressions' value from the 'Metric' column.
df3_Table1 = dfmerge_table[dfmerge_table['Metric'] == 'Impressions']
df3_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [22]:
#--Step3.Using groupby extracting data's of 'Impressions' value from the 'Metric' column for all the 'model'.
df3_Table1.groupby('Metric')['Model'].value_counts()

Metric       Model
Impressions  Pathfinder     9554
             Armada         7342
             Rogue          7281
             Altima         7206
             Kicks          4766
             Sentra         4012
             Multi-Model     738
Name: count, dtype: int64

In [23]:
#--Step4.Extracting 'model' for maximum 'Impressions'.
df3_Table1.groupby('Metric')['Model'].value_counts().head(1)

Metric       Model
Impressions  Pathfinder    9554
Name: count, dtype: int64

In [24]:
#--3.Find out the top 3 campaigns in terms of impressions for every message type.

In [25]:
#--Step1.Merging two tables using primary key.
dfmerge1_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge1_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [26]:
#--Step2.Filtering 'Impressions' value from the 'Metric' column.
df4_Table1 = dfmerge1_table[dfmerge1_table['Metric'] == 'Impressions']
df4_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [27]:
#--Step3.Extracting 'Campaign' value counts in terms of 'Impressions' for every message type using groupby.
df5_Table1 = df4_Table1.groupby(['Message type','Metric'])['Campaign'].value_counts()
df5_Table1

Message type   Metric       Campaign
Future Market  Impressions  Rogue campaign 4         2010
                            Altima campaign 3        1828
                            Rogue campaign 2         1641
                            Rogue campaign 5         1520
                            Sentra campaign 3        1403
                            Kicks campaign 4         1395
                            Sentra campaign 1        1318
                            Kicks campaign 3         1295
                            Altima campaign 2        1280
                            Rogue campaign 1         1000
                            Kicks campaign 6          837
                            Altima campaign 5         836
                            Altima campaign 1         818
                            shop at home              738
                            Kicks campaign 5          706
                            Rogue pre launch          648
                            Rogue campaign 3          462
                            Altima campaign 4         332
                            Altima campaign 6         303
                            Sentra campaign 4         152
                            Sentra campaign 2         143
Near Market    Impressions  Armada campaign 2        4464
                            Pathfinder campaign 2    1890
                            Armada campaign 4        1800
                            Pathfinder campaign 7    1444
                            Pathfinder campaign 8    1434
                            Pathfinder campaign 5    1418
                            Pathfinder campaign 6    1418
                            Altima campaign 8         997
                            Armada campaign 3         842
                            Pathfinder campaign 1     840
                            Altima campaign 7         812
                            Pathfinder campaign 4     630
                            Pathfinder campaign 3     480
                            Kicks campaign 1          276
                            Kicks campaign 2          257
                            Armada campaign 1         236
                            Sentra campaign 11         59
                            Sentra campaign 14         59
                            Sentra campaign 17         58
                            Sentra campaign 7          57
                            Sentra campaign 20         56
                            Sentra campaign 15         55
                            Sentra campaign 22         55
                            Sentra campaign 18         53
                            Sentra campaign 21         53
                            Sentra campaign 9          52
                            Sentra campaign 19         51
                            Sentra campaign 12         50
                            Sentra campaign 13         46
                            Sentra campaign 23         46
                            Sentra campaign 24         44
                            Sentra campaign 6          44
                            Sentra campaign 8          42
                            Sentra campaign 16         38
                            Sentra campaign 5          33
                            Sentra campaign 25         26
                            Sentra campaign 10         19
Name: count, dtype: int64

In [28]:
#--Step4.Extracting top 3 'Campaign' in terms of 'Impressions' for every message type.
df5_Table1.groupby(['Message type']).head(3)

Message type   Metric       Campaign
Future Market  Impressions  Rogue campaign 4         2010
                            Altima campaign 3        1828
                            Rogue campaign 2         1641
Near Market    Impressions  Armada campaign 2        4464
                            Pathfinder campaign 2    1890
                            Armada campaign 4        1800
Name: count, dtype: int64

In [29]:
#--4.Does the campaign with maximum impressions also have maximum clicks?

In [30]:
#--Step1.Filtering 'Impressions' and 'Clicks' value from the 'Metric' column.
df6_Table1 = df_Table1[df_Table1['Metric'].isin(['Impressions', 'Clicks'])]
df6_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
5,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Clicks,0.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123692,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Clicks,102.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.0,30,9,2021

In [31]:
#--Step2.Using group by to extract the 'Campaign' with maximum 'Impressions' and 'Clicks'.
df7_Table1 = df6_Table1.groupby('Metric')['Campaign'].value_counts()
df7_Table1

Metric       Campaign
Clicks       Armada campaign 2        4464
             Rogue campaign 4         2010
             Pathfinder campaign 2    1890
             Altima campaign 3        1828
             Armada campaign 4        1800
                                      ...
Impressions  Sentra campaign 8          42
             Sentra campaign 16         38
             Sentra campaign 5          33
             Sentra campaign 25         26
             Sentra campaign 10         19
Name: count, Length: 116, dtype: int64

In [32]:
#--Step3.Extracting 'Campaign' with maximum 'Impressions' and 'Campaign' with maximum 'Clicks'.
     #--Yes,campaign with maximum impressions also have maximum clicks.
df7_Table1.groupby('Metric').head(1)

Metric       Campaign
Clicks       Armada campaign 2    4464
Impressions  Armada campaign 2    4464
Name: count, dtype: int64

In [33]:
#--5.Find out the top 3 campaigns in terms of CPM (CPM stands for cost per mile which means cost per 1000 impressions. 
#--CPM = total media cost/total impressions * 1000)

In [34]:
#--Step1.Filtering 'Impressions' value from the 'Metric' column.
df8_Table1 = df_Table1[df_Table1['Metric'] == 'Impressions']
df8_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [35]:
#--Step2.Creating a new column as 'Total Impressions' in terms of 'Impressions' and 'Campaign'.
df9_Table1 = df8_Table1.groupby('Campaign')['Metric'].value_counts().reset_index(name='Total Impressions')
df9_Table1

                 Campaign       Metric  Total Impressions
0       Altima campaign 1  Impressions                818
1       Altima campaign 2  Impressions               1280
2       Altima campaign 3  Impressions               1828
3       Altima campaign 4  Impressions                332
4       Altima campaign 5  Impressions                836
5       Altima campaign 6  Impressions                303
6       Altima campaign 7  Impressions                812
7       Altima campaign 8  Impressions                997
8       Armada campaign 1  Impressions                236
9       Armada campaign 2  Impressions               4464
10      Armada campaign 3  Impressions                842
11      Armada campaign 4  Impressions               1800
12       Kicks campaign 1  Impressions                276
13       Kicks campaign 2  Impressions                257
14       Kicks campaign 3  Impressions               1295
15       Kicks campaign 4  Impressions               1395
16       Kicks campaign 5  Impressions                706
17       Kicks campaign 6  Impressions                837
18  Pathfinder campaign 1  Impressions                840
19  Pathfinder campaign 2  Impressions               1890
20  Pathfinder campaign 3  Impressions                480
21  Pathfinder campaign 4  Impressions                630
22  Pathfinder campaign 5  Impressions               1418
23  Pathfinder campaign 6  Impressions               1418
24  Pathfinder campaign 7  Impressions               1444
25  Pathfinder campaign 8  Impressions               1434
26       Rogue campaign 1  Impressions               1000
27       Rogue campaign 2  Impressions               1641
28       Rogue campaign 3  Impressions                462
29       Rogue campaign 4  Impressions               2010
30       Rogue campaign 5  Impressions               1520
31       Rogue pre launch  Impressions                648
32      Sentra campaign 1  Impressions               1318
33     Sentra campaign 10  Impressions                 19
34     Sentra campaign 11  Impressions                 59
35     Sentra campaign 12  Impressions                 50
36     Sentra campaign 13  Impressions                 46
37     Sentra campaign 14  Impressions                 59
38     Sentra campaign 15  Impressions                 55
39     Sentra campaign 16  Impressions                 38
40     Sentra campaign 17  Impressions                 58
41     Sentra campaign 18  Impressions                 53
42     Sentra campaign 19  Impressions                 51
43      Sentra campaign 2  Impressions                143
44     Sentra campaign 20  Impressions                 56
45     Sentra campaign 21  Impressions                 53
46     Sentra campaign 22  Impressions                 55
47     Sentra campaign 23  Impressions                 46
48     Sentra campaign 24  Impressions                 44
49     Sentra campaign 25  Impressions                 26
50      Sentra campaign 3  Impressions               1403
51      Sentra campaign 4  Impressions                152
52      Sentra campaign 5  Impressions                 33
53      Sentra campaign 6  Impressions                 44
54      Sentra campaign 7  Impressions                 57
55      Sentra campaign 8  Impressions                 42
56      Sentra campaign 9  Impressions                 52
57           shop at home  Impressions                738

In [36]:
#--Step3.Sorting the 'Total Impressions' values.
df10_Table1 = df9_Table1.sort_values(by='Total Impressions', ascending=False)
df10_Table1

                 Campaign       Metric  Total Impressions
9       Armada campaign 2  Impressions               4464
29       Rogue campaign 4  Impressions               2010
19  Pathfinder campaign 2  Impressions               1890
2       Altima campaign 3  Impressions               1828
11      Armada campaign 4  Impressions               1800
27       Rogue campaign 2  Impressions               1641
30       Rogue campaign 5  Impressions               1520
24  Pathfinder campaign 7  Impressions               1444
25  Pathfinder campaign 8  Impressions               1434
23  Pathfinder campaign 6  Impressions               1418
22  Pathfinder campaign 5  Impressions               1418
50      Sentra campaign 3  Impressions               1403
15       Kicks campaign 4  Impressions               1395
32      Sentra campaign 1  Impressions               1318
14       Kicks campaign 3  Impressions               1295
1       Altima campaign 2  Impressions               1280
26       Rogue campaign 1  Impressions               1000
7       Altima campaign 8  Impressions                997
10      Armada campaign 3  Impressions                842
18  Pathfinder campaign 1  Impressions                840
17       Kicks campaign 6  Impressions                837
4       Altima campaign 5  Impressions                836
0       Altima campaign 1  Impressions                818
6       Altima campaign 7  Impressions                812
57           shop at home  Impressions                738
16       Kicks campaign 5  Impressions                706
31       Rogue pre launch  Impressions                648
21  Pathfinder campaign 4  Impressions                630
20  Pathfinder campaign 3  Impressions                480
28       Rogue campaign 3  Impressions                462
3       Altima campaign 4  Impressions                332
5       Altima campaign 6  Impressions                303
12       Kicks campaign 1  Impressions                276
13       Kicks campaign 2  Impressions                257
8       Armada campaign 1  Impressions                236
51      Sentra campaign 4  Impressions                152
43      Sentra campaign 2  Impressions                143
37     Sentra campaign 14  Impressions                 59
34     Sentra campaign 11  Impressions                 59
40     Sentra campaign 17  Impressions                 58
54      Sentra campaign 7  Impressions                 57
44     Sentra campaign 20  Impressions                 56
46     Sentra campaign 22  Impressions                 55
38     Sentra campaign 15  Impressions                 55
45     Sentra campaign 21  Impressions                 53
41     Sentra campaign 18  Impressions                 53
56      Sentra campaign 9  Impressions                 52
42     Sentra campaign 19  Impressions                 51
35     Sentra campaign 12  Impressions                 50
36     Sentra campaign 13  Impressions                 46
47     Sentra campaign 23  Impressions                 46
53      Sentra campaign 6  Impressions                 44
48     Sentra campaign 24  Impressions                 44
55      Sentra campaign 8  Impressions                 42
39     Sentra campaign 16  Impressions                 38
52      Sentra campaign 5  Impressions                 33
49     Sentra campaign 25  Impressions                 26
33     Sentra campaign 10  Impressions                 19

In [37]:
#--Step4.Filtering 'Media Cost' value from the 'Metric' column.
df11_Table1 = df_Table1[df_Table1['Metric'] == 'Media Cost']
df11_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123685,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021
123688,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021
123691,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021

In [38]:
#--Step5.Creating a new column as 'Total Media Cost' in terms of 'Media Cost' and 'Campaign'.
df12_Table1 = df11_Table1.groupby('Campaign')['Metric'].value_counts().reset_index(name='Total Media Cost')
df12_Table1

                 Campaign      Metric  Total Media Cost
0       Altima campaign 1  Media Cost               818
1       Altima campaign 2  Media Cost              1280
2       Altima campaign 3  Media Cost              1828
3       Altima campaign 4  Media Cost               332
4       Altima campaign 5  Media Cost               836
5       Altima campaign 6  Media Cost               303
6       Altima campaign 7  Media Cost               812
7       Altima campaign 8  Media Cost               997
8       Armada campaign 1  Media Cost               236
9       Armada campaign 2  Media Cost              4464
10      Armada campaign 3  Media Cost               842
11      Armada campaign 4  Media Cost              1800
12       Kicks campaign 1  Media Cost               276
13       Kicks campaign 2  Media Cost               257
14       Kicks campaign 3  Media Cost              1295
15       Kicks campaign 4  Media Cost              1395
16       Kicks campaign 5  Media Cost               706
17       Kicks campaign 6  Media Cost               837
18  Pathfinder campaign 1  Media Cost               840
19  Pathfinder campaign 2  Media Cost              1890
20  Pathfinder campaign 3  Media Cost               480
21  Pathfinder campaign 4  Media Cost               630
22  Pathfinder campaign 5  Media Cost              1418
23  Pathfinder campaign 6  Media Cost              1418
24  Pathfinder campaign 7  Media Cost              1444
25  Pathfinder campaign 8  Media Cost              1434
26       Rogue campaign 1  Media Cost              1000
27       Rogue campaign 2  Media Cost              1641
28       Rogue campaign 3  Media Cost               462
29       Rogue campaign 4  Media Cost              2010
30       Rogue campaign 5  Media Cost              1520
31       Rogue pre launch  Media Cost               648
32      Sentra campaign 1  Media Cost              1318
33     Sentra campaign 10  Media Cost                19
34     Sentra campaign 11  Media Cost                59
35     Sentra campaign 12  Media Cost                50
36     Sentra campaign 13  Media Cost                46
37     Sentra campaign 14  Media Cost                59
38     Sentra campaign 15  Media Cost                55
39     Sentra campaign 16  Media Cost                38
40     Sentra campaign 17  Media Cost                58
41     Sentra campaign 18  Media Cost                53
42     Sentra campaign 19  Media Cost                51
43      Sentra campaign 2  Media Cost               143
44     Sentra campaign 20  Media Cost                56
45     Sentra campaign 21  Media Cost                53
46     Sentra campaign 22  Media Cost                55
47     Sentra campaign 23  Media Cost                46
48     Sentra campaign 24  Media Cost                44
49     Sentra campaign 25  Media Cost                26
50      Sentra campaign 3  Media Cost              1403
51      Sentra campaign 4  Media Cost               152
52      Sentra campaign 5  Media Cost                33
53      Sentra campaign 6  Media Cost                44
54      Sentra campaign 7  Media Cost                57
55      Sentra campaign 8  Media Cost                42
56      Sentra campaign 9  Media Cost                52
57           shop at home  Media Cost               706

In [39]:
#--Step6.Sorting the 'Total Media Cost' values.
df13_Table1 = df12_Table1.sort_values(by='Total Media Cost', ascending=False)
df13_Table1

                 Campaign      Metric  Total Media Cost
9       Armada campaign 2  Media Cost              4464
29       Rogue campaign 4  Media Cost              2010
19  Pathfinder campaign 2  Media Cost              1890
2       Altima campaign 3  Media Cost              1828
11      Armada campaign 4  Media Cost              1800
27       Rogue campaign 2  Media Cost              1641
30       Rogue campaign 5  Media Cost              1520
24  Pathfinder campaign 7  Media Cost              1444
25  Pathfinder campaign 8  Media Cost              1434
23  Pathfinder campaign 6  Media Cost              1418
22  Pathfinder campaign 5  Media Cost              1418
50      Sentra campaign 3  Media Cost              1403
15       Kicks campaign 4  Media Cost              1395
32      Sentra campaign 1  Media Cost              1318
14       Kicks campaign 3  Media Cost              1295
1       Altima campaign 2  Media Cost              1280
26       Rogue campaign 1  Media Cost              1000
7       Altima campaign 8  Media Cost               997
10      Armada campaign 3  Media Cost               842
18  Pathfinder campaign 1  Media Cost               840
17       Kicks campaign 6  Media Cost               837
4       Altima campaign 5  Media Cost               836
0       Altima campaign 1  Media Cost               818
6       Altima campaign 7  Media Cost               812
57           shop at home  Media Cost               706
16       Kicks campaign 5  Media Cost               706
31       Rogue pre launch  Media Cost               648
21  Pathfinder campaign 4  Media Cost               630
20  Pathfinder campaign 3  Media Cost               480
28       Rogue campaign 3  Media Cost               462
3       Altima campaign 4  Media Cost               332
5       Altima campaign 6  Media Cost               303
12       Kicks campaign 1  Media Cost               276
13       Kicks campaign 2  Media Cost               257
8       Armada campaign 1  Media Cost               236
51      Sentra campaign 4  Media Cost               152
43      Sentra campaign 2  Media Cost               143
37     Sentra campaign 14  Media Cost                59
34     Sentra campaign 11  Media Cost                59
40     Sentra campaign 17  Media Cost                58
54      Sentra campaign 7  Media Cost                57
44     Sentra campaign 20  Media Cost                56
46     Sentra campaign 22  Media Cost                55
38     Sentra campaign 15  Media Cost                55
45     Sentra campaign 21  Media Cost                53
41     Sentra campaign 18  Media Cost                53
56      Sentra campaign 9  Media Cost                52
42     Sentra campaign 19  Media Cost                51
35     Sentra campaign 12  Media Cost                50
36     Sentra campaign 13  Media Cost                46
47     Sentra campaign 23  Media Cost                46
53      Sentra campaign 6  Media Cost                44
48     Sentra campaign 24  Media Cost                44
55      Sentra campaign 8  Media Cost                42
39     Sentra campaign 16  Media Cost                38
52      Sentra campaign 5  Media Cost                33
49     Sentra campaign 25  Media Cost                26
33     Sentra campaign 10  Media Cost                19

In [40]:
#--Step7.Merging 'Total Impressions' and 'Total Media Cost' in terms of 'Campaign'.
dfmerge2_table = pd.merge(df10_Table1 , df13_Table1 , on = 'Campaign')
dfmerge2_table

,Campaign,Metric_x,Total Impressions,Metric_y,Total Media Cost
0,Armada campaign 2,Impressions,4464,Media Cost,4464
1,Rogue campaign 4,Impressions,2010,Media Cost,2010
2,Pathfinder campaign 2,Impressions,1890,Media Cost,1890
3,Altima campaign 3,Impressions,1828,Media Cost,1828
4,Armada campaign 4,Impressions,1800,Media Cost,1800
5,Rogue campaign 2,Impressions,1641,Media Cost,1641
6,Rogue campaign 5,Impressions,1520,Media Cost,1520
7,Pathfinder campaign 7,Impressions,1444,Media Cost,1444
8,Pathfinder campaign 8,Impressions,1434,Media Cost,1434
9,Pathfinder campaign 6,Impressions,1418,Media Cost,1418
10,Pathfinder campaign 5,Impressions,1418,Media Cost,1418
11,Sentra campaign 3,Impressions,1403,Media Cost,1403
12,Kicks campaign 4,Impressions,1395,Media Cost,1395
13,Sentra campaign 1,Impressions,1318,Media Cost,1318
14,Kicks campaign 3,Impressions,1295,Media Cost,1295
15,Altima campaign 2,Impressions,1280,Media Cost,1280
16,Rogue campaign 1,Impressions,1000,Media Cost,1000
17,Altima campaign 8,Impressions,997,Media Cost,997
18,Armada campaign 3,Impressions,842,Media Cost,842
19,Pathfinder campaign 1,Impressions,840,Media Cost,840
20,Kicks campaign 6,Impressions,837,Media Cost,837
21,Altima campaign 5,Impressions,836,Media Cost,836
22,Altima campaign 1,Impressions,818,Media Cost,818
23,Altima campaign 7,Impressions,812,Media Cost,812
24,shop at home,Impressions,738,Media Cost,706
25,Kicks campaign 5,Impressions,706,Media Cost,706
26,Rogue pre launch,Impressions,648,Media Cost,648
27,Pathfinder campaign 4,Impressions,630,Media Cost,630
28,Pathfinder campaign 3,Impressions,480,Media Cost,480
29,Rogue campaign 3,Impressions,462,Media Cost,462
30,Altima campaign 4,Impressions,332,Media Cost,332
31,Altima campaign 6,Impressions,303,Media Cost,303
32,Kicks campaign 1,Impressions,276,Media Cost,276
33,Kicks campaign 2,Impressions,257,Media Cost,257
34,Armada campaign 1,Impressions,236,Media Cost,236
35,Sentra campaign 4,Impressions,152,Media Cost,152
36,Sentra campaign 2,Impressions,143,Media Cost,143
37,Sentra campaign 14,Impressions,59,Media Cost,59
38,Sentra campaign 11,Impressions,59,Media Cost,59
39,Sentra campaign 17,Impressions,58,Media Cost,58
40,Sentra campaign 7,Impressions,57,Media Cost,57
41,Sentra campaign 20,Impressions,56,Media Cost,56
42,Sentra campaign 22,Impressions,55,Media Cost,55
43,Sentra campaign 15,Impressions,55,Media Cost,55
44,Sentra campaign 21,Impressions,53,Media Cost,53
45,Sentra campaign 18,Impressions,53,Media Cost,53
46,Sentra campaign 9,Impressions,52,Media Cost,52
47,Sentra campaign 19,Impressions,51,Media Cost,51
48,Sentra campaign 12,Impressions,50,Media Cost,50
49,Sentra campaign 13,Impressions,46,Media Cost,46
50,Sentra campaign 23,Impressions,46,Media Cost,46
51,Sentra campaign 6,Impressions,44,Media Cost,44
52,Sentra campaign 24,Impressions,44,Media Cost,44
53,Sentra campaign 8,Impressions,42,Media Cost,42
54,Sentra campaign 16,Impressions,38,Media Cost,38
55,Sentra campaign 5,Impressions,33,Media Cost,33
56,Sentra campaign 25,Impressions,26,Media Cost,26
57,Sentra campaign 10,Impressions,19,Media Cost,19

In [41]:
#--Step8.Creating a new column as 'CPM' in terms 'Campaign'.
dfmerge2_table['CPM'] = (dfmerge2_table['Total Media Cost'] / dfmerge2_table['Total Impressions']) * 1000

In [42]:
#--Step9.Filtering top 3 'Campaign' in terms of 'CPM'. 
dfmerge2_table.head(3)

,Campaign,Metric_x,Total Impressions,Metric_y,Total Media Cost,CPM
0,Armada campaign 2,Impressions,4464,Media Cost,4464,1000.0
1,Rogue campaign 4,Impressions,2010,Media Cost,2010,1000.0
2,Pathfinder campaign 2,Impressions,1890,Media Cost,1890,1000.0

In [43]:
#--6.What is the monthly average media cost for different media types?

In [44]:
#--Step1.Filtering 'Media Cost' value from the 'Metric' column.
df14_Table1 = df_Table1[df_Table1['Metric'] == 'Media Cost']
df14_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123685,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021
123688,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021
123691,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021

In [45]:
#--Step2.Extracting monthly average 'Media Cost' for different 'Media Type'.
df14_Table1.groupby(['Media Type','Metric'])['month'].mean()

Media Type    Metric
Display       Media Cost    5.805577
Online Video  Media Cost    7.200568
Name: month, dtype: float64

In [46]:
#--7.Which media type is more expensive in terms of CPM?

In [47]:
#--Step1.Merging two tables using primary key.
dfmerge3_table = pd.merge(df_Table1, df_Table2 , on ='Campaign')
dfmerge3_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [48]:
#--Step2.Checking for the unique values in 'Media Type'.
dfmerge3_table['Media Type'].unique()

array(['Display', 'Online Video'], dtype=object)

In [49]:
#--Step3.Filtering 'Media Cost' value from the 'Metric' column.
df15_Table1 = dfmerge3_table[dfmerge3_table['Metric'] == 'Media Cost']
df15_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019,Near Market,Kicks
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019,Near Market,Kicks
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122615,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021,Near Market,Pathfinder
122618,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021,Near Market,Pathfinder
122621,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021,Near Market,Pathfinder
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder

In [50]:
#--Step4.Creating a new column as 'Total Media Cost' in terms of 'Media Type'.
df16_Table1 = df15_Table1.groupby('Media Type')['Metric'].value_counts().reset_index(name='Total Media Cost')
df16_Table1

     Media Type      Metric  Total Media Cost
0       Display  Media Cost              7746
1  Online Video  Media Cost             33121

In [51]:
#--Step5.Filtering 'Impressions' value from the 'Metric' column.
df17_Table1 = dfmerge3_table[dfmerge3_table['Metric'] == 'Impressions']
df17_Table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [52]:
#--Step6.Creating a new column as 'Total Impressions' in terms of 'Media Type'.
df18_Table1 = df17_Table1.groupby('Media Type')['Metric'].value_counts().reset_index(name='Total Impressions')
df18_Table1

     Media Type       Metric  Total Impressions
0       Display  Impressions               7778
1  Online Video  Impressions              33121

In [53]:
#--Step7.Merging 'Total Impressions' and 'Total Media Cost' in terms of 'Media Type'.
dfmerge4_table = pd.merge(df16_Table1 , df18_Table1 , on = 'Media Type')
dfmerge4_table

     Media Type    Metric_x  Total Media Cost     Metric_y  Total Impressions
0       Display  Media Cost              7746  Impressions               7778
1  Online Video  Media Cost             33121  Impressions              33121

In [54]:
#--Step8.Creating a new column as 'CPM' in terms 'Media Type'.
dfmerge4_table['CPM'] = ((dfmerge4_table['Total Media Cost'] / dfmerge4_table['Total Impressions']) * 1000)
dfmerge4_table

,Media Type,Metric_x,Total Media Cost,Metric_y,Total Impressions,CPM
0,Display,Media Cost,7746,Impressions,7778,995.885832
1,Online Video,Media Cost,33121,Impressions,33121,1000.000000

In [55]:
#--Step9.Sorting the 'CPM' values to find out the expensive 'Media Type'.
dfmerge4_table.sort_values(by='CPM', ascending=False)[:1]

,Media Type,Metric_x,Total Media Cost,Metric_y,Total Impressions,CPM
1,Online Video,Media Cost,33121,Impressions,33121,1000.0